### PR TITLE
Add helk update script

### PR DESCRIPTION
**Pull request by devdua**
**What is this PR for?**
This adds an update script (helk_update.sh) for HELK, which creates an updated fresh installation by checking for updates to the local images with those hosted on Docker Hub.

**What type of PR is it?**
Feature Request

**How should this be tested?**
It can be tested by either 
1. Publishing a new image on Docker Hub and then running the update script
2. Forced downgrade:
- Stopping a running container and deleting the corresponding image of any of the current latest local HELK images
- Pulling an existing older image on Docker Hub so that the update script can detect that
- Running the helk_update.sh script

helk-updater

**Questions:**
* Do the licenses files need update? No
* Are there breaking changes for older versions? No
* Does this needs documentation? Yes

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
This is awesome @devdua !! Thank you very much. I will test it soon and pull this 👍 Once again thank you for contributing to the project! Sorry for the late response. I have been traveling for the past couple of weeks.

**Comment by rsimplicio** [comment]
@devdua see my PR #78 for suggested changes to memory checking of the install script to prevent an error when you have enough "available" memory, but not enough "free" memory, if you intend to do that sort of checking. I do see that's not currently in the update script, so please feel free to ignore if that's the case.

**Comment by Cyb3rWard0g** [comment]
@devdua since you are starting the HELK after the update, it would be great to add @rsimplicio changes he made to make sure we consider the resources of the server before rebuilding the HELK.  Let me know if it makes sense

**Comment by devdua** [comment]
@Cyb3rWard0g @rsimplicio that definitely makes sense and is a great suggestion, thanks! I'll spend some time and add a resource check before restarting the HELK - probably both an available memory check and a disk space check.

**Comment by devdua** [comment]
@Cyb3rWard0g I have improved the update process and made it compatible with HELK 6.3.0... Also I have added the check for available memory, keeping it the same as the install script. However, I figured that checking for disk space might not be needed, as an older image would be deleted and replaced by the newer, updated image if found (even if it's slightly larger in size). Is that ok? What do you think?

**Comment by Cyb3rWard0g** [comment]
This is awesome @devdua !!! I have one question. How would this work when Elastic releases a new docker images. I am now using Elastic official Docker Images for the ELK piece. I felt that just using the ELK docker images directly from elastic and local Dockerfiles for any extra configs is easier.  I will not be using HELK ELK docker images anymore. Once again, just for the ELK piece. the reason is because it is easy to keep everything local from an ELK perspective to allow custom pipelines and other configs. I was wondering if the update script that you created would have to be only used when HELK uses updated versions of elastic images. However, what if Elastic images are one version ahead of HELK due to the fact that HELK has not been updated yet? I think that the update script will push HELK to use latest ELK images that have not been tested yet. I am making the whole build more modular and easier to reconfigure with custom settings. Let me know if this makes sense. I really like the update script to automate a full build upgrade. Do you think that it would be better to have a version file for all the components and play with that file? comparing the old version file with the latest one after doing a git pull?? That way you know if there are any changes and simply apply the changes??

**Comment by devdua** [comment]
@Cyb3rWard0g I gave it the same thought, and decided not to update the Elastic stack since you made that change in v6.3. I figured that since that is the core of the HELK project, it would be wise to maintain a tested config. The script just uses the existing docker-compose.yml config to build HELK again. The script only checks for updates to images that are hosted on your account on Docker Hub, plus any extension images like helk-sigma that are hosted on any other Docker Hub account.

This produces the desired effect - ELK will not be updated unless you change the docker-compose config to use custom ELK images. Since you have changed that to 3 separate Dockerfiles to pull from the official repository, the update script ignores that. Earlier, since you were hosting those custom helk-elk images on your account, the script was checking for updates to them as well. But now it won't.

**Comment by devdua** [comment]
Here's the update script output, it checks for only the 7 custom Docker images that you host, or any other extension images - 
update script v3

**Comment by Cyb3rWard0g** [comment]
yeah thats what I was thinking. I figured it would be easier to have the ELK piece local with Dockerfiles. Do you think that it would make sense to still have the update script but playing with **git**? For example, if there are any new updates available from the master/origin, run the script by doing first a pull and then gracefully terminate the HELK if it is running and run the newer script?? Is it possible? I have not looked into anything to automate the updates. Let me know. Sorry for the recent changes. I have jus had recent questions and comments about how difficult is to have a custom ELK when I host everything in Dockerhub and things like that.

**Comment by devdua** [comment]
Sure, that can be done as well. 

I'll modify the script soon, and push the changes.

**Comment by Cyb3rWard0g** [comment]
Thank you very much @devdua . I really appreciate your help on this one. I am not sure if you know any other method to update a Docker build. I was just throwing some ideas, but never tested. 👍 Thank you!

**Comment by devdua** [comment]
I did look into that, found a project called Watchtower but I thought that won't be a very good option. So I thought of going this way & checking against Docker Hub for updates.

I could keep both GitHub and Docker Hub as an option if that is ok. For example, the user could choose where to update from -

1. Github (Stable, Recommended)
2. Docker Hub

If this doesn't make sense, I'll keep Github as the only option. Is that ok?

**Comment by devdua** [comment]
I have added the GitHub update option, @Cyb3rWard0g please test whenever you can 😄 

update script - github

**Comment by Cyb3rWard0g** [comment]
@devdua I think the Github option makes sense since that one updates the whole build. Thats awesome I will test it soon.

**Comment by devdua** [comment]
Hey @Cyb3rWard0g did you get a chance to test it?  Any issues?

**Comment by Cyb3rWard0g** [comment]
Hey @devdua sorry I have been really busy with other things that I couldnt get to it. I will try to test it this week. Were you able to test it with the latest updates I pushed last couple of days. Also, I think we should only have the github option by default and no only to docker images in docker hub. 👍

**Comment by devdua** [comment]
Yes I had tested with the latest updates you have pushed, and I have now also removed the Docker Hub update option.

**Comment by Cyb3rWard0g** [comment]
@devdua I added the flexibility to set an Elastic License: basic or trial. Check the new update. I dont know if that is something that needs to be added to your script. I now have two docker-compose files (trial and basic). Let me know if you have any questions. I really appreciate your help with this script. From now on, the HELK will have those two licenses available during the install process. Therefore, I believe we also have to add that flexibility when the user updates the HELK. Let me know if this makes sense. thank you again 👍

**Comment by Cyb3rWard0g** [comment]
This is the last commit: https://github.com/Cyb3rWard0g/HELK/commit/931d56729f965cd7973a963f792139dd572bb7c5

**Comment by devdua** [comment]
Sure @Cyb3rWard0g I will add that functionality.

**Comment by devdua** [comment]
Hi @Cyb3rWard0g I have made the changes, I hope the script works according to your expectation.

**Comment by Cyb3rWard0g** [comment]
Hey @devdua yes sorry I got really busy with a few projects and conferences and classes :( sorry for the late response. Take a look at the new updates for the HELK:
+ we know check for Docker Disk space
+ Jupyter Token is not needed anymore since I moved it to Jupyter Hub

Im not sure if it would be better to keep the script simple with only memory, license and disk check.

**Comment by devdua** [comment]
Yes yes that's alright! I have made the changes to align the script with the new update. I have also added the docker disk check as discussed in #99 .

**Comment by devdua** [comment]
Hi @Cyb3rWard0g is there anything else that's causing this PR to be on hold? I'd be happy to work it out

**Comment by Cyb3rWard0g** [comment]
Hey @devdua ! I think it should be good to be merged. One thing, Can you provide a quick document with basics steps? similar to https://github.com/Cyb3rWard0g/HELK/wiki/Installation (A very short one. I am interested on showing what the user will see on their screens) . I will then add a wiki page with the basic steps and how users can use the script. That will also help to have a latest test before merging this PR 👍  Thank you very much for your patience!!

**Comment by devdua** [comment]
Hi! 
Commands to be run:
```
cd $HELK_DIR/docker
sudo ./helk_update.sh
```
If updates are available and pulled, the script will ask for the license to be used for updating the HELK (like in the install script). Using this way, users can even switch from the basic to the trial license. Default choice is basic. Once this choice is confirmed, the script stops the existing HELK instance and attempts to rebuild it using the pulled updates. 

Log location: `/var/log/helk-update.log`

Log contents when updates install fine -
```
Git is available
HELK repo exists
Fetching origin
Fetching upstream
From https://github.com/Cyb3rWard0g/HELK
   a15f047..3741d20  master     -> upstream/master
Fetching helk-repo
From https://github.com/Cyb3rWard0g/HELK
   a15f047..3741d20  master     -> helk-repo/master
Possibly new release available. Commit diff --> 2
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 17 and 12 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
From https://github.com/Cyb3rWard0g/HELK
 * branch            master     -> FETCH_HEAD
Updating a15f047..3741d20
Fast-forward
 .../pipeline/1543-winevent-conversions-process-cli-filter.conf | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)
Stopping helk-kafka-broker  ... done
Stopping helk-kafka-broker2 ... done
Stopping helk-logstash      ... done
Stopping helk-nginx         ... done
Stopping helk-spark-worker2 ... done
Stopping helk-spark-worker  ... done
Stopping helk-zookeeper     ... done
Stopping helk-jupyter       ... done
Stopping helk-kibana        ... done
Stopping helk-spark-master  ... done
Stopping helk-elasticsearch ... done
Removing helk-kafka-broker  ... done
Removing helk-kafka-broker2 ... done
Removing helk-logstash      ... done
Removing helk-nginx         ... done
Removing helk-spark-worker2 ... done
Removing helk-spark-worker  ... done
Removing helk-zookeeper     ... done
Removing helk-jupyter       ... done
Removing helk-kibana        ... done
Removing helk-spark-master  ... done
Removing helk-elasticsearch ... done
Removing network docker_helk
Pulling helk-elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:6.4.0)...
6.4.0: Pulling from elasticsearch/elasticsearch
Digest: sha256:2244676001fa9b12012ec1f7a51526a8d7384fcb02674e5ae29b6e637e363908
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:6.4.0
Pulling helk-spark-master (cyb3rward0g/helk-spark-master:2.3.1-c)...
2.3.1-c: Pulling from cyb3rward0g/helk-spark-master
Digest: sha256:6e2a6226953f1e5495549352256559c114015578aaca16407236119b9f4d85f3
Status: Downloaded newer image for cyb3rward0g/helk-spark-master:2.3.1-c
Pulling helk-spark-worker (cyb3rward0g/helk-spark-worker:2.3.1-c)...
2.3.1-c: Pulling from cyb3rward0g/helk-spark-worker
Digest: sha256:cb049e44bdae029a08adf1d950a08d28938d91571de60a56cb688019f3154930
Status: Downloaded newer image for cyb3rward0g/helk-spark-worker:2.3.1-c
Pulling helk-jupyter (cyb3rward0g/helk-jupyter:0.0.6)...
0.0.6: Pulling from cyb3rward0g/helk-jupyter
Digest: sha256:1d8f691a29bbfa85ce5c99c8dfdd1add01bb3b2b66da3611264165d9f8cbcc52
Status: Downloaded newer image for cyb3rward0g/helk-jupyter:0.0.6
Pulling helk-kibana (docker.elastic.co/kibana/kibana:6.4.0)...
6.4.0: Pulling from kibana/kibana
Digest: sha256:e61c1122d9bc8dc8a113c79a035cf3c34d09674685f550ec842afc2d923ad568
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:6.4.0
Pulling helk-nginx (cyb3rward0g/helk-nginx:0.0.7)...
0.0.7: Pulling from cyb3rward0g/helk-nginx
Digest: sha256:8cdbbd5084f1b7b046af7080a6aea0bf6be0d0e623d990107b9932f7404384e0
Status: Downloaded newer image for cyb3rward0g/helk-nginx:0.0.7
Pulling helk-zookeeper (cyb3rward0g/helk-zookeeper:2.0.0-a)...
2.0.0-a: Pulling from cyb3rward0g/helk-zookeeper
Creating helk-elasticsearch ... done
Status: Downloaded newer image for cyb3rward0g/helk-zookeeper:2.0.0-a
Pulling helk-kafka-broker (cyb3rward0g/helk-kafka-broker:2.0.0-b)...
Creating helk-spark-master ... done
Digest: sha256:c6318ddb3fb11174747bdc973bd8336a05afce3c45197be037c9823045411351
Creating helk-kibana ... done
Creating helk-jupyter ... done
Creating helk-zookeeper ... done
Digest: sha256:40bbb687fc820c892906fd325ad9ffacb96a56ab252a919fd2a60f315b374af1
Status: Downloaded newer image for docker.elastic.co/logstash/logstash:6.4.0
Creating helk-kafka-broker2 ... done
Creating helk-kibana ... 
Creating helk-spark-master ... 
Creating helk-jupyter ... 
Creating helk-spark-worker2 ... 
Creating helk-spark-worker ... 
Creating helk-zookeeper ... 
Creating helk-nginx ... 
Creating helk-kafka-broker2 ... 
Creating helk-kafka-broker ... 
Creating helk-logstash ... 
```
If the update is successful, it will look like this -
```
[HELK-UPDATE-INFO] Checking GitHub for updates...
[HELK-UPDATE-INFO] New release available. Pulling new code.
[HELK-UPDATE-INFO] Set HELK License. Default value is basic: basic
[HELK-UPDATE-INFO] Stopping HELK and starting update
[HELK-UPDATE-INFO] Rebuilding HELK via docker-compose
[HELK-UPDATE-INFO] Rebuild succeeded, waiting 180 seconds for services to start...
[HELK-UPDATE-INFO] YOUR HELK HAS BEEN UPDATED!
```
Or if updates are already pulled - 
updates-installed-2

There are some scenarios where the HELK might not update. Here are a few basic scenarios - 

1. Updates not available
updates-not-available

2. Updates available, but not enough resources available (memory/disk space)
update-when-resources-not-enough

3. Updates available, and downloaded, but not enough resources available (memory/disk space)
update-when-updates-already-downloaded

4. docker/docker-compose related issues (will be highlighted in the update log)

**Comment by Cyb3rWard0g** [comment]
Thank you very much @devdua . I will add that to the wiki 👍

**Pull request merged**
