### PR TITLE
Update helk_install.sh to read from available memory instead of free

### PR DESCRIPTION
**Pull request by rsimplicio**
**What is this PR for?**
Updates helk_install.sh to read from the available memory rather than the free memory. This resolves an issue that's encountered when you re-install HELK after shutting down a previous version of HELK, due to cached files in memory lowering the "free" memory counter but having enough "available" memory.

Closes: #77
 
**What type of PR is it?**
Bug Fix

**How should this be tested?**

Run helk_install.sh on a system that has less than 12GB of "Free" memory, but greater than 12GB "Available" memory as reported by:
`free -hm`

**Questions:**
* Do the licenses files need update? No
* Are there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
Nicee. Makes sense. the problem with that was that I wanted to make sure we consider the available memory since people might be installing it in a server that already has other applications running. However, I think that it makes sense to do it by the available memory. One thing that I would like to point is that you consider the **Disk Size** part. You are using an old config. it should keep : 
```
df -m | awk '$NF=="/"{printf "%.f\t\t", $4 / 1024
```
check https://github.com/Cyb3rWard0g/HELK/issues/67 . Please make sure your helk_install is up to date.

**Comment by rsimplicio** [comment]
I've merged in your upstream changes, and ensured the line you highlighted was updated. This is my first PR so please let me know if anything else is missing.

**Comment by Cyb3rWard0g** [comment]
Quick question @rsimplicio . If the HELK will calculate memory size based on available memory, what happens when someone has a server with 14GB of memory but it only has 6GB free. The HELK will fail with other errors (i.e. elasticsearch starting up..). I think that Free memory is better since I wont have to worry about how the server was built or what extra applications it has when it is built. If I do available memory, I think there are more use cases that could make the build fail rather than always making sure first that you have enough memory for HELK. If you are updating HELK I think that it can be done in this other PR that someone else is working on. For example, there we can add this change so that when you are updating HELK and rebuilding a new version, it takes the available memory since the free memory is already being used by cached files in memory. Does it make sense?? Im trying to reduce the amount of times the build fails when it is being installed for the first time.

**Comment by Cyb3rWard0g** [comment]
ohhhhh @rsimplicio thank you very much for the details. Makes sense 😄 👍 . Ok I will add the PR. I think it would be good to also add it to the updated script. Would you mind helping @devdua with that update to his PR??

**Pull request merged**
