### PR TITLE
New import script + saved objects

### PR DESCRIPTION
**Pull request by troplolBE**
**What is this PR for?**
This PR is for full support of Kibana 7 and contains:
- the dashboards converted to Kibana 7
- a new way of importing saved objects compliant with Kibana 7
- a script to export all current objects from Kibana

**What type of PR is it?**
[Update]

**How should this be tested?**
Try to make a new install with this branch and see if everything gets imported properly.

**Questions:**
* Do the licenses files need update? No
* Are there breaking changes for older versions? Not sure
* Does this needs documentation? No

### CODE REVIEW

**Comment by troplolBE** [comment]
[Finish PR and execute full install test with new import scripts/methods](https://trello.com/c/E3Urq8Dc/246-finish-pr-and-execute-full-install-test-with-new-import-scripts-methods)

**Comment by troplolBE** [comment]
PR is now ready for review.

**Comment by Cyb3rWard0g** [comment]
Hey @troplolBE ! Thank you very much for the hard work and contributions ! I really appreciate it. Would you mind checking the conflict files?

**Comment by troplolBE** [comment]
> Hey @troplolBE ! Thank you very much for the hard work and contributions ! I really appreciate it. Would you mind checking the conflict files?

Hey @Cyb3rWard0g ! I actually removed those files from my repo so there shouldn't be any errors but I think this error persists because of changes made in a previous commit that I don't have in my branch.

**Pull request merged**
