### PR TITLE
Updated helk_update.sh

### PR DESCRIPTION
**Pull request by devdua**
**What is this PR for?**
Bring helk_update.sh script up-to-date with current release

**What type of PR is it?**
Bug Fix

**How should this be tested?**
In terminal, change directory to `$HELK_DIR/docker` and run `sudo bash helk_update.sh`

**Questions:**
* Do the licenses files need update? No
* Are there breaking changes for older versions? No
* Does this needs documentation? No

### CODE REVIEW

**Comment by devdua** [comment]
@Cyb3rWard0g please test this, I want to make sure I haven't missed anything in the script and that it updates the deployment in a stable manner. Cheers ✌

**Comment by devdua** [comment]
Hi @Cyb3rWard0g did you get a chance to test it? I'd be happy to iron out issues if any.

**Comment by Cyb3rWard0g** [comment]
Yes sorry for the late response @devdua . I will be available this weekend to go over all the issues and PRs. Thank you for this . I really appreciate it!

**Comment by neu5ron** [comment]
I as well on the testing, this will be critical in new update too 🙃 thank you @devdua

**Comment by devdua** [comment]
Hi @Cyb3rWard0g @neu5ron did you guys get a chance to test this out?

**Comment by neu5ron** [comment]
@devdua many moons later I got to test..
lets chat at some point, but we all need to come together on trial and custom modifications and the usability for users who don't know git to well
PR was merged into #391 and I added/modified some stuff

**Pull request merged**
